
title = "博客"
zhandian="巴蒂博客"
author = "bati8888"
#copyright = "2020-2021"
description = "山重水复，柳暗花明"
#profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
publishDir = "docs"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["blog" ,"tech"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006/1/2"
indexDateFormat = "2006/1/2"
listDateFormat = "2006/1/2"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
 readMore = true
# postSectionName = "blog"
fullPostContent=false


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.


# [[socialIcons]]
# icon = "fab fa-github"
# title = "GitHub"
# url = "https://github.com/lxndrblz/anatole/"



#[[socialIcons]]
# icon = "fas fa-envelope"
# title = "e-mail"
# url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-weibo"
#title = "e-mail"
#url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-weixin"
#title = "e-mail"
#url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-tiktok"
#title = "e-mail"
#url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-zhihu"
#title = "e-mail"
#url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-qq"
#title = "e-mail"
#url = "mailto:mail@example.com"

#[[socialIcons]]
#icon = "fab fa-bilibili"
#title = "e-mail"
#url = "mailto:mail@example.com"

